development:
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: url_shortner
  charset: utf8
  collation: utf8_bin

staging:
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: url_shortner
  charset: utf8
  collation: utf8_bin

production:
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: url_shortner
  charset: utf8
  collation: utf8_bin